server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: ea29ca17c377a0e4b29be0fdbc46059ea6a380d21a88b747dc34e314c630afe8
    url: jdbc:postgresql://ec2-3-213-228-206.compute-1.amazonaws.com:5432/deahun18gi89o7
    username: uuhaxsbwdbjjde
  jpa:
    hibernate:
      # ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: elephantsuite@gmail.com
    password: drltvibfcnottodw

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
