server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 9cb4184ccfe17f8632cd224089b9fedeaf2bd35d25d6144d7b44742820ca4e0e
    url: jdbc:postgresql://ec2-34-194-40-194.compute-1.amazonaws.com:5432/dcpov6s7t4arn8
    username: ubzzrikvhtgfdr
  jpa:
    hibernate:
       ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: elephantnoreply@gmail.com
    password: ccbqsesqvrdvxzjo

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
